### ISSUE TITLE
Azure.RequestFailedException: The SSL connection could not be established

### ISSUE THREAD

**Issue by abhinpai** [microsoft/kernel-memory#127]
I'm encountering an issue while attempting to run the kernel-memory example **https://github.com/microsoft/kernel-memory/tree/main/examples/200-dotnet-nl2sql** in my machine configured with OpenAI settings. The problem arises during the application startup, and it results in an Azure.RequestFailedException. Below, you'll find the stack trace of the exception.

I've attempted to address this problem by providing a custom HttpClient. Here's the code snippet I've used to configure the HttpClient. Despite these efforts, the issue still persists

      private static KernelBuilder ConfigureOpenAi(
              string apikey,
              string? modelCompletion,
              string? modelEmbedding,
              ILoggerFactory? loggerFactory)
          {
        
        using var handler = new HttpClientHandler();
        
        handler.ClientCertificateOptions = ClientCertificateOption.Manual;
        handler.CheckCertificateRevocationList = false;
        handler.ServerCertificateCustomValidationCallback = (_, cert, cetChain, _) => true;

        using var client = new HttpClient(handler);

        var builder = new KernelBuilder();

        if (loggerFactory != null)
        {
            builder.WithLoggerFactory(loggerFactory);
        }

        modelCompletion ??= DefaultChatModel;
        modelEmbedding ??= DefaultEmbedModel;
        
        builder
            .WithMemoryStorage(new VolatileMemoryStore())
            .WithOpenAITextEmbeddingGenerationService(modelEmbedding, apikey);

        if (!modelCompletion.StartsWith("gpt", StringComparison.OrdinalIgnoreCase))
        {
            return builder.WithOpenAITextCompletionService(modelCompletion, apikey);
        }

        return builder.WithOpenAIChatCompletionService(modelCompletion, apikey, httpClient: client);
    } 

**Stack Trace**

`
    Azure.RequestFailedException: The SSL connection could not be established, see inner exception.
     ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
     ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
       at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
       at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
       at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
       at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
       at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
       at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
       --- End of inner exception stack trace ---
       at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
       at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
       at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
`

**Comment by dluc** [comment]
@crickman ^^
