### ISSUE TITLE
Search There was an error while searching--update to 0.22.231216.1 

### ISSUE THREAD

**Issue by strikene** [microsoft/kernel-memory#212]
I upgraded from 0.15 to 0.22
 I'm using SimpleQueues, SimpleFileStorage, SimpleVectorDb in 0.15 and when I upgrade to 0.22 I get an error searching for it.

At this point, 0.22webserver uses the data generated by 0.15. If I use the data generated by brand new 0.22 I don't have this issue, is it that I missed some necessary upgrade step?
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMVVJ2BUR57O", Request id "0HMVVJ2BUR57O:00000001": An unhandled exception was thrown by the application.
      System.Collections.Generic.KeyNotFoundException: The given key 'url' was not present in the dictionary.
         at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
         at Microsoft.KernelMemory.Search.SearchClient.SearchAsync(String index, String query, ICollection`1 filters, Double minRelevance, Int32 limit, CancellationToken cancellationToken)
         at WorkerService1.Program.<> c.<< Main > b__0_7 > d.MoveNext() in C: \Program.cs:line 316
      -- - End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<> c__DisplayClass90_2.<< HandleRequestBodyAndCompileRequestDelegateForJson > b__2 > d.MoveNext()
      -- - End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.< Invoke > g__AwaitRequestTask | 6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

VectorDbFile in 0.15 
"payload":{"file":"content.txt","emb_src_file":"content.txt.partition.0.txt","last_update":"2023-11-12T06:45:25","vector_provider":"OpenAI.TextEmbedding.AzureTextEmbeddingGeneration","vector_generator":"TODO","text":"Initialize"}
VectorDbFile in 0.22
"payload":{"file":"content.txt","url":"","text":"Initialize"}

**Comment by dluc** [comment]
Fixed in nuget version 0.23.231219.1
