### ISSUE TITLE
[Bug] No handlers found for step 'extract'

### ISSUE THREAD

**Issue by doggy8088** [microsoft/kernel-memory#340]
### Context / Scenario

I started `kernelmemory/service` container with the following command:

```ps1
docker run -v "$(PWD)/files:/app/files" -v "$(PWD)/vdb:/app/vdb" -v "$(PWD)/appsettings.Development.json:/app/appsettings.Production.json" -it --rm -p 9001:9001 kernelmemory/service
```

My config is:

```json
{
  "KernelMemory": {
    "Service": {
      "RunWebService": true,
      "RunHandlers": true,
      "OpenApiEnabled": true,
      "Handlers": {}
    },
    "ContentStorageType": "SimpleFileStorage",
    "TextGeneratorType": "AzureOpenAIText",
    "ServiceAuthorization": {
      "Enabled": false,
      "AuthenticationType": "APIKey",
      "HttpHeaderName": "Authorization",
      "AccessKey1": "",
      "AccessKey2": ""
    },
    "DataIngestion": {
      "OrchestrationType": "InProcess",
      "DistributedOrchestration": {
        "QueueType": ""
      },
      "EmbeddingGenerationEnabled": true,
      "EmbeddingGeneratorTypes": [
        "AzureOpenAIEmbedding"
      ],
      "MemoryDbTypes": [
        "SimpleVectorDb"
      ],
      "ImageOcrType": "None",
      "TextPartitioning": {
        "MaxTokensPerParagraph": 1000,
        "MaxTokensPerLine": 300,
        "OverlappingTokens": 100
      },
      "DefaultSteps": []
    },
    "Retrieval": {
      "MemoryDbType": "SimpleVectorDb",
      "EmbeddingGeneratorType": "AzureOpenAIEmbedding",
      "SearchClient": {
        "MaxAskPromptSize": -1,
        "MaxMatchesCount": 100,
        "AnswerTokens": 300,
        "EmptyAnswer": "INFO NOT FOUND"
      }
    },
    "Services": {
      "SimpleFileStorage": {
        "Directory": "/app/files",
        "StorageType": "Disk"
      },
      "AzureOpenAIEmbedding": {
        "APIType": "EmbeddingGeneration",
        "Auth": "ApiKey",
        "Endpoint": "https://<res>.openai.azure.com/",
        "Deployment": "text-embedding-ada-002",
        "APIKey": "<api-key>"
      },
      "SimpleVectorDb": {
        "Directory": "/app/vdb",
        "StorageType": "Disk"
      },
      "AzureOpenAIText": {
        "APIType": "ChatCompletion",
        "Auth": "ApiKey",
        "Endpoint": "https://<res>.openai.azure.com/",
        "Deployment": "gpt-35-turbo",
        "APIKey": "<api-key>",
        "MaxRetries": 10
      }
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Trace"
    }
  },
  "AllowedHosts": "*"
}
```

### What happened?

My client code:

```cs
var memory = new MemoryWebClient("http://127.0.0.1:9001/");
await memory.ImportTextAsync("123");
```

My server log:

```log
***************************************************************************************************************************
* Environment         : Production
* Web service         : Enabled
* Web service auth    : Disabled
* Pipeline handlers   : Enabled
* OpenAPI swagger     : Enabled
* Logging level       : Trace
* Memory Db           : Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb
* Content storage     : Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage
* Embedding generation: Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator
* Text generation     : Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextGenerator
***************************************************************************************************************************
info: Microsoft.KernelMemory.ServiceAssembly[0]
      Starting Kernel Memory service, .NET Env: Production, Log Level: Trace, Web service: True, Auth: False, Pipeline handlers: True
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.KernelMemory.Handlers.DeleteGeneratedFilesHandler[0]
      Handler 'delete_generated_files' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: delete_generated_files
info: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Handler 'extract' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: extract
info: Microsoft.KernelMemory.Handlers.GenerateEmbeddingsHandler[0]
      Handler 'gen_embeddings' ready, 1 embedding generators
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: gen_embeddings
info: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Handler 'partition' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: partition
info: Microsoft.KernelMemory.Handlers.DeleteDocumentHandler[0]
      Handler 'private_delete_document' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: private_delete_document
info: Microsoft.KernelMemory.Handlers.DeleteIndexHandler[0]
      Handler 'private_delete_index' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: private_delete_index
info: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Handler save_records ready, 1 vector storages
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: save_records
info: Microsoft.KernelMemory.Handlers.SummarizationHandler[0]
      Handler 'summarize' ready
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler as service created: summarize
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: delete_generated_files
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: extract
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: gen_embeddings
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: partition
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: private_delete_document
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: private_delete_index
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: save_records
info: Microsoft.KernelMemory.HandlerAsAHostedService[0]
      Handler service started: summarize
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:9001'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:9001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      New upload HTTP request
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Queueing upload of 1 files for further processing [request ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961]
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Uploading 1 files, pipeline 'default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961'
dbug: Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage[0]
      Creating directory /app/files/default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Uploading file 'content.txt', size 3 bytes
trce: Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage[0]
      Writing file to /app/files/default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961/content.txt
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      File uploaded: content.txt, 3 bytes
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961/__pipeline_status.json'
trce: Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage[0]
      Writing file to /app/files/default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961/__pipeline_status.json
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961/__pipeline_status.json'
trce: Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage[0]
      Writing file to /app/files/default/ed93ce3a7032476ba0ffd469e28eb8bb202403050239120371961/__pipeline_status.json
fail: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Pipeline start failed
      Microsoft.KernelMemory.Pipeline.OrchestrationException: No handlers found for step 'extract'
         at Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, CancellationToken cancellationToken)
```

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Windows + Docker Desktop + WSL2 backend

```txt
C:\>ver

Microsoft Windows [Version 10.0.19045.4046]
```

![image](https://github.com/microsoft/kernel-memory/assets/88981/9bbf4923-b38c-4e83-90d6-e899c946fe4e)

```txt
C:\>wsl --version
WSL 版本： 2.0.14.0
核心版本： 5.15.133.1-1
WSLg 版本： 1.0.59
MSRDC 版本： 1.2.4677
Direct3D 版本： 1.611.1-81528511
DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows 版本： 10.0.19045.4046
```

Client:

C# / .NET 8

### Relevant log output

```shell
see above.
```

**Comment by doggy8088** [comment]
During setup phrase:

```sh
docker run -it --rm -v  "$(PWD)/appsettings.Development.json:/app/appsettings.Development.json" --entrypoint dotnet kernelmemory/service Microsoft.KernelMemory.ServiceAssembly.dll setup
```

In this question:

> How should memory ingestion be orchestrated?

I answered: `In process orchestration, all .NET handlers run synchronously`

That seems the root cause of my issue. It because after I switch to `Using asynchronous distributed queues (allows to mix handlers written in different languages)`, the error message is gone.

![image](https://github.com/microsoft/kernel-memory/assets/88981/ec7e7b1e-89f5-4ae1-974d-d9fcbb36fb87)

I don't really understand what's the `In process orchestration, all .NET handlers run synchronously` exact mean? I can't make a API call when choosing this?

**Comment by dluc** [comment]
@doggy8088 as you discovered, it's a regression affecting the service when you choose to run requests synchronously. 
This question:
> How should memory ingestion be orchestrated?

is about the way documents are imported, e.g. whether you prefer the import to run Synchronously, without queues, blocking the web API call until the document is processes, or Asynchronously, with queues, without blocking the web API call. Normally the web service is configured to use queues, so web clients don't have to wait, and more importantly queues allow to retry in case of transient errors. 

I would suggest using the asynchronous queue for now, we'll fix the bug soon.

**Comment by dluc** [comment]
Fixed in #346
