### ISSUE TITLE
[Bug] System.ArgumentException: Input span arguments must all have the same length.

### ISSUE THREAD

**Issue by doggy8088** [microsoft/kernel-memory#367]
### Context / Scenario

My `appsettings.Development.json`:

```json
{
  "KernelMemory": {
    "Service": {
      "RunWebService": true,
      "RunHandlers": false,
      "OpenApiEnabled": true,
      "Handlers": {
        "extract": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.TextExtractionHandler"
        },
        "partition": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.TextPartitioningHandler"
        },
        "gen_embeddings": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.GenerateEmbeddingsHandler"
        },
        "save_records": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.SaveRecordsHandler"
        },
        "summarize": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.SummarizationHandler"
        },
        "delete_generated_files": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.DeleteGeneratedFilesHandler"
        },
        "private_delete_document": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.DeleteDocumentHandler"
        },
        "private_delete_index": {
          "Assembly": "Microsoft.KernelMemory.Core.dll",
          "Class": "Microsoft.KernelMemory.Handlers.DeleteIndexHandler"
        },
        "disabled_handler_example": {
          "Assembly": "",
          "Class": ""
        }
      }
    },
    "ContentStorageType": "SimpleFileStorage",
    "TextGeneratorType": "AzureOpenAIText",
    "DefaultIndexName": "default",
    "ServiceAuthorization": {
      "Enabled": false,
      "AuthenticationType": "APIKey",
      "HttpHeaderName": "Authorization",
      "AccessKey1": "",
      "AccessKey2": ""
    },
    "DataIngestion": {
      "OrchestrationType": "InProcess",
      "DistributedOrchestration": {
        "QueueType": ""
      },
      "EmbeddingGenerationEnabled": false,
      "EmbeddingGeneratorTypes": [],
      "MemoryDbTypes": [
        "SimpleVectorDb"
      ],
      "ImageOcrType": "None",
      "TextPartitioning": {
        "MaxTokensPerParagraph": 1000,
        "MaxTokensPerLine": 300,
        "OverlappingTokens": 100
      },
      "DefaultSteps": []
    },
    "Retrieval": {
      "MemoryDbType": "SimpleVectorDb",
      "EmbeddingGeneratorType": "AzureOpenAIEmbedding",
      "SearchClient": {
        "MaxAskPromptSize": -1,
        "MaxMatchesCount": 100,
        "AnswerTokens": 300,
        "EmptyAnswer": "INFO NOT FOUND",
        "Temperature": 0.0,
        "TopP": 0.0,
        "PresencePenalty": 0.0,
        "FrequencyPenalty": 0.0,
        "StopSequences": [],
        "TokenSelectionBiases": {}
      }
    },
    "Services": {
      "SimpleFileStorage": {
        "StorageType": "Volatile",
        "Directory": "_files"
      },
      "SimpleQueues": {
        "StorageType": "Volatile",
        "Directory": "_queues"
      },
      "SimpleVectorDb": {
        "StorageType": "Volatile",
        "Directory": "_vectors"
      },
      "AzureBlobs": {
        "Auth": "AzureIdentity",
        "Account": "",
        "Container": "smemory",
        "ConnectionString": "",
        "EndpointSuffix": "core.windows.net"
      },
      "AzureQueues": {
        "Auth": "AzureIdentity",
        "Account": "",
        "ConnectionString": "",
        "EndpointSuffix": "core.windows.net"
      },
      "RabbitMQ": {
        "Host": "127.0.0.1",
        "Port": "5672",
        "Username": "user",
        "Password": "",
        "VirtualHost": "/"
      },
      "AzureAISearch": {
        "Auth": "AzureIdentity",
        "Endpoint": "https://<...>",
        "APIKey": ""
      },
      "Postgres": {
        "ConnectionString": "Host=localhost;Port=5432;Username=public;Password=",
        "TableNamePrefix": "km-"
      },
      "Qdrant": {
        "Endpoint": "http://127.0.0.1:6333",
        "APIKey": ""
      },
      "Redis": {
        "ConnectionString": "",
        "Tags": {
          "type": ",",
          "user": ",",
          "ext": ","
        }
      },
      "Elasticsearch": {
        "CertificateFingerPrint": "",
        "Endpoint": "",
        "UserName": "",
        "Password": "",
        "IndexPrefix": "",
        "ShardCount": 1,
        "Replicas": 0
      },
      "AzureOpenAIText": {
        "APIType": "ChatCompletion",
        "Auth": "ApiKey",
        "Endpoint": "https://XXX.openai.azure.com/",
        "Deployment": "gpt-4",
        "APIKey": "XXX",
        "MaxRetries": 10
      },
      "AzureOpenAIEmbedding": {
        "Auth": "ApiKey",
        "Endpoint": "https://XXX.openai.azure.com/",
        "APIKey": "XXX",
        "Deployment": "text-embedding-3-large",
        "MaxTokenTotal": 8191,
        "APIType": "EmbeddingGeneration"
      },
      "OpenAI": {
        "TextModel": "gpt-3.5-turbo-16k",
        "TextModelMaxTokenTotal": 16384,
        "EmbeddingModel": "text-embedding-ada-002",
        "EmbeddingModelMaxTokenTotal": 8191,
        "APIKey": "",
        "OrgId": "",
        "MaxRetries": 10
      },
      "LlamaSharp": {
        "ModelPath": "",
        "MaxTokenTotal": 4096
      },
      "AzureAIDocIntel": {
        "Auth": "AzureIdentity",
        "APIKey": "",
        "Endpoint": ""
      }
    }
  },
  "Logging": {
    "LogLevel": {
      "Microsoft.AspNetCore": "Warning",
      "Default": "Warning"
    }
  }
}
```

I use the latest docker image:

```ps1
docker pull kernelmemory/service
```

Startup command:

```ps1
docker run -it --rm -v "$(PWD)/_vectors:/app/_vectors" -v "$(PWD)/_files:/app/_files" -v "$(PWD)/appsettings.Development.json:/app/appsettings.Production.json" -p 9001:9001 --entrypoint dotnet kernelmemory/service Microsoft.KernelMemory.ServiceAssembly.dll
```

### What happened?

In my config, the `"StorageType"` set to `Volatile` which will cause api failed to response Ask request.

I can import text without error:

```cs
var memory = new MemoryWebClient("http://127.0.0.1:9001/");
await memory.ImportTextAsync("My name is Will. I live in Taiwan.");
```

I can't ask:

```cs
var memory = new MemoryWebClient("http://127.0.0.1:9001/");
var result = await memory.AskAsync("Where does the Will live?");
```

Here is the error from the console in the container:

```txt
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN25IPJ8LI0G", Request id "0HN25IPJ8LI0G:00000001": An unhandled exception was thrown by the application.
      System.ArgumentException: Input span arguments must all have the same length.
         at System.ThrowHelper.ThrowArgument_SpansMustHaveSameLength()
         at System.Numerics.Tensors.TensorPrimitives.CosineSimilarity(ReadOnlySpan`1 x, ReadOnlySpan`1 y)
         at Microsoft.KernelMemory.Embedding.CosineSimilarity(Embedding embedding)
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Service.WebAPIEndpoints.<>c.<<UseAskEndpoint>b__7_0>d.MoveNext() in /src/service/Service/WebAPIEndpoints.cs:line 205
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|80_0[T](Task`1 task)
         at Microsoft.KernelMemory.Service.HttpAuthEndpointFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in /src/service/Service/Auth/HttpAuthHandler.cs:line 38
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|109_0(ValueTask`1 valueTask, HttpContext httpContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass90_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

Windows 10, C#, Microsoft.KernelMemory.Core 0.34.240313.1, Docker Image `kernelmemory/service:latest`

### Relevant log output

Here is the full Trace log when I run the server build from latest source code.

```shell
***************************************************************************************************************************
* Environment         : Development
* Memory type         : Sync - Microsoft.KernelMemory.MemoryServerless
* Pipeline handlers   : 8 synchronous / 0 asynchronous
* Web service         : Enabled
* Web service auth    : Disabled
* OpenAPI swagger     : Enabled
* Memory Db           : Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb
* Content storage     : Microsoft.KernelMemory.ContentStorage.DevTools.SimpleFileStorage
* Embedding generation: Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator
* Text generation     : Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextGenerator
* Log level           : Trace
***************************************************************************************************************************
info: Microsoft.KernelMemory.ServiceAssembly[0]
      Starting Kernel Memory service, .NET Env: Development, Log Level: Trace, Web service: True, Auth: False, Pipeline handlers: False
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://*:8080'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:9001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /src/kernel-memory/service/Service
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      New upload HTTP request, content length 532
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      Index ''
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Queueing upload of 1 files for further processing [request 7f2699eccca64056844d2e8e8f81bce4202403160538181121602]
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Uploading 1 files, pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Uploading file 'content.txt', size 34 bytes
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      File uploaded: content.txt, 34 bytes
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
dbug: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Extracting text, pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
dbug: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Extracting text from plain text file content.txt
dbug: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Saving extracted text file content.txt.extract.txt
dbug: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Saving extracted content content.txt.extract.json
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'extract' processed pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602' successfully
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
dbug: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Partitioning text, pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
dbug: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Partitioning text file content.txt.extract.txt
dbug: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Saving 1 file partitions
dbug: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Partition size: 10 tokens
trce: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Skipping file content.txt.extract.json (not original text)
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'partition' processed pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602' successfully
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
trce: Microsoft.KernelMemory.Handlers.GenerateEmbeddingsHandler[0]
      Embedding generation is disabled, skipping - pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'gen_embeddings' processed pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602' successfully
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
dbug: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Saving memory records, pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
trce: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Creating index 'default'
trce: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Saving record d=7f2699eccca64056844d2e8e8f81bce4202403160538181121602//p=46c68c575fd748f6aad584cf7ddbbeb1 in index 'default'
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Handler 'save_records' processed pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602' successfully
dbug: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Saving pipeline status to 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602/__pipeline_status.json'
info: Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator[0]
      Pipeline 'default/7f2699eccca64056844d2e8e8f81bce4202403160538181121602' complete
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      Doc Id '7f2699eccca64056844d2e8e8f81bce4202403160538181121602'
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      New search request, index '(null)', minRelevance 0
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Fetching relevant memories
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: Input span arguments must all have the same length.
         at System.ThrowHelper.ThrowArgument_SpansMustHaveSameLength()
         at System.Numerics.Tensors.TensorPrimitives.CosineSimilarity(ReadOnlySpan`1 x, ReadOnlySpan`1 y)
         at Microsoft.KernelMemory.Embedding.CosineSimilarity(Embedding embedding)
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Service.WebAPIEndpoints.<>c.<<UseAskEndpoint>b__7_0>d.MoveNext() in /src/kernel-memory/service/Service/WebAPIEndpoints.cs:line 210
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|92_0[T](Task`1 task)
         at Microsoft.KernelMemory.Service.HttpAuthEndpointFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in /src/kernel-memory/service/Service/Auth/HttpAuthHandler.cs:line 38
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by dluc** [comment]
@doggy8088 did you try different embedding models during your tests? different models often output different embedding sizes, which can result in that error

**Comment by doggy8088** [comment]
@dluc I tried `text-embedding-ada-002` model. The same error.

**Comment by dluc** [comment]
did you also try other models? when using multiple models they might have different embedding size, that will lead to that error.

**Comment by doggy8088** [comment]
@dluc I tried the latest source that contains your #369 commit, but the error is the same.

```log
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      Doc Id '6120150152ac44478f498ef297b29e64202403190343105055967'
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      New search request, index '(null)', minRelevance 0
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Fetching relevant memories
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: Input span arguments must all have the same length.
         at System.ThrowHelper.ThrowArgument_SpansMustHaveSameLength()
         at System.Numerics.Tensors.TensorPrimitives.CosineSimilarity(ReadOnlySpan`1 x, ReadOnlySpan`1 y)
         at Microsoft.KernelMemory.Embedding.CosineSimilarity(Embedding embedding)
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Service.WebAPIEndpoints.<>c.<<UseAskEndpoint>b__7_0>d.MoveNext() in /src/kernel-memory/service/Service/WebAPIEndpoints.cs:line 210
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|92_0[T](Task`1 task)
         at Microsoft.KernelMemory.Service.HttpAuthEndpointFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in /src/kernel-memory/service/Service/Auth/HttpAuthHandler.cs:line 38
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

You can see my `appsettings.Development.json` above. I don't use any other embedding models.

All I used is two models below:

```json
      "AzureOpenAIText": {
        "APIType": "ChatCompletion",
        "Auth": "ApiKey",
        "Endpoint": "https://XXX.openai.azure.com/",
        "Deployment": "gpt-4",
        "APIKey": "XXX",
        "MaxRetries": 10
      },
      "AzureOpenAIEmbedding": {
        "Auth": "ApiKey",
        "Endpoint": "https://XXX.openai.azure.com/",
        "APIKey": "XXX",
        "Deployment": "text-embedding-3-large",
        "MaxTokenTotal": 8191,
        "APIType": "EmbeddingGeneration"
      },
```

**Comment by dluc** [comment]
Could you try again with the latest changes in the repo? The error message should change and show the embeddings size.

Old error message:
> System.ArgumentException: Input span arguments must all have the same length.

New error message:
> System.InvalidOperationException: Embedding vectors must have the same length to calculate cosine similarity. Embedding 1 length: ... ; Embedding 2 length: ... .

**Comment by doggy8088** [comment]
Yes, I see new error message now. See below:

```log
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      Doc Id 'd7abd5a5a32a4e1ab19344e43b170de1202403190730466713932'
trce: Microsoft.KernelMemory.Service.WebAPIEndpoints.WebAPIEndpoint[0]
      New search request, index '(null)', minRelevance 0
trce: Microsoft.KernelMemory.Search.SearchClient[0]
      Fetching relevant memories
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Embedding vectors must have the same length to calculate cosine similarity. Embedding 1 length: 3072; Embedding 2 length: 1536.
         at Microsoft.KernelMemory.Embedding.CosineSimilarity(Embedding embedding)
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryStorage.DevTools.SimpleVectorDb.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Service.WebAPIEndpoints.<>c.<<UseAskEndpoint>b__7_0>d.MoveNext() in /src/kernel-memory/service/Service/WebAPIEndpoints.cs:line 210
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<TaskOfTToValueTaskOfObject>g__ExecuteAwaited|92_0[T](Task`1 task)
         at Microsoft.KernelMemory.Service.HttpAuthEndpointFilter.InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next) in /src/kernel-memory/service/Service/Auth/HttpAuthHandler.cs:line 38
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<ExecuteValueTaskOfObject>g__ExecuteAwaited|129_0(ValueTask`1 valueTask, HttpContext httpContext, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by doggy8088** [comment]
It works now. Thank you so much!

There are two folders I mounted into the container:

1. "$(PWD)/_vectors"
2. "$(PWD)/_files"

It because I tried so many times with various embedding models. I didn't realize that embeddings vectors saved locally.
