### ISSUE TITLE
[Question] Timeout when connecting to Postgres

### ISSUE THREAD

**Issue by vicperdana** [microsoft/kernel-memory#445]
### Context / Scenario

Trying to use the Postgres [connector](https://microsoft.github.io/kernel-memory/extensions/memory-db/postgres), and getting an issue to connect to the database.  There may steps that I have missed. 

### Question

See the following code and the resulting error. 
```Csharp
var postgresConfig = new PostgresConfig();
        var config = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .AddJsonFile("appsettings.Development.json", optional: true)
            .Build()
            .BindSection("KernelMemory:Services:Postgres", postgresConfig);

        var memory = new KernelMemoryBuilder()
            .WithPostgresMemoryDb(postgresConfig)
            .WithOpenAITextEmbeddingGeneration(new OpenAIConfig
            {
                APIKey = config.GetSection("KernelMemory:Services:OpenAI:APIKey").Value,
                EmbeddingModel = "text-embedding-3-small"
            })
            .WithOpenAITextGeneration(new OpenAIConfig
            {
                APIKey = config.GetSection("KernelMemory:Services:OpenAI:APIKey").Value,
                TextModel = config.GetSection("KernelMemory:Services:OpenAI:TextModel").Value
            })
            .Build();
            //**** This is causing the error ****
            var response = await memory.SearchAsync(message);
```

Error
```
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlReadBuffer.<Ensure>g__EnsureLong|54_0(NpgsqlReadBuffer buffer, Int32 count, Boolean async, Boolean readingNotifications)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.GetSimilarAsync(String tableName, Vector target, Double minSimilarity, String filterSql, Dictionary`2 sqlUserValues, Int32 limit, Int32 offset, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.KernelMemory.Postgres.Db.PostgresDbClient.GetSimilarAsync(String tableName, Vector target, Double minSimilarity, String filterSql, Dictionary`2 sqlUserValues, Int32 limit, Int32 offset, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.KernelMemory.Postgres.PostgresMemory.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.KernelMemory.Postgres.PostgresMemory.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.KernelMemory.Postgres.PostgresMemory.GetSimilarListAsync(String index, String text, ICollection`1 filters, Double minRelevance, Int32 limit, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
   at Microsoft.KernelMemory.Search.SearchClient.AskAsync(String index, String question, ICollection`1 filters, Double minRelevance, CancellationToken cancellationToken)
   at AspireShop.ChatService.Controllers.ChatController.GetMemory(String message) in /somedir/ChatController.cs:line 175
   at lambda_method6(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   ```

**Comment by dluc** [comment]
@vicperdana could you include the configuration details (leaving out secrets)?

it could be a networking issue, e.g. about the hostname/IP used.

when working locally, I use this:

```json

      "Postgres": {
        "ConnectionString": "Host=localhost;Port=5432;Username=public;Password=",
        "TableNamePrefix": "km-"
      },
```

**Comment by vicperdana** [comment]
@dluc see below.

```
"KernelMemory": {
    "Services": {
      "OpenAI": {
        "TextModel" : "gpt-3.5-turbo",
        "EmbeddingModel" : "text-embedding-ada-002",
        "APIKey": "******"
      },
      "Postgres": {
        "ConnectionString": "Host=localhost;Port=52242;Username=*******;Password=********;Database=catalogdb"
      }
      
```

**Comment by dluc** [comment]
are you running postgres with Docker or natively? (I run postgres natively on my machine) If docker, are you sharing the network, exposing the ports, etc?

**Comment by vicperdana** [comment]
Hi @dluc 

With Docker, I can connect fine locally from my machine. Is there any way to validate connection with KM?  I suspect with Aspire, this port is dynamically changed.

```
psql 'host=localhost port=62419 dbname=catalogdb user=**** password=****'
psql (16.2)
Type "help" for help.

catalogdb=# 
```

**Comment by vicperdana** [comment]
Solved this by using `env.Var()` instead. 
`postgresConfig.ConnectionString = Env.Var("ConnectionStrings__catalogdb");`
