### ISSUE TITLE
[Bug] Simultaneous execution of AskDocument & ImportDocument fails

### ISSUE THREAD

**Issue by aropb** [microsoft/kernel-memory#764]
### Context / Scenario

Simultaneous execution of Ask Document & Import Document fails.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Cannot use this SafeLLamaContextHandle - it has been disposed'.
at LLama.Native.SafeLLamaContextHandle.ThrowIfDisposed()
at LLama.Native.SafeLLamaContextHandle.GetLogitsIth(Int32 i)
at LLama.StatelessExecutor.InferAsync(String prompt, IInferenceParams inferenceParams, CancellationToken cancellationToken)+MoveNext()
at LLama.StatelessExecutor.InferAsync(String prompt, IInferenceParams inferenceParams, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
at Microsoft.KernelMemory.Handlers.SummarizationHandler.SummarizeAsync(String content, IContext context)
at Microsoft.KernelMemory.Handlers.SummarizationHandler.SummarizeAsync(String content, IContext context)
at Microsoft.KernelMemory.Handlers.SummarizationHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken)
at Microsoft.KernelMemory.Pipeline.InProcessPipelineOrchestrator.RunPipelineAsync(DataPipeline pipeline, CancellationToken cancellationToken)
at Microsoft.KernelMemory.Pipeline.BaseOrchestrator.ImportDocumentAsync(String index, DocumentUploadRequest uploadRequest, IContext context, CancellationToken cancellationToken)

### What happened?

It works.

### Importance

a fix would make my life easier

### Platform, Language, Versions

Operating system: Windows 11
.NET runtime version: 8.0.8
LLamaSharp version: 0.16.0
KernelMemory: 0.71...
CUDA version (if you are using cuda backend): 12
CPU & GPU device: CPU or GPU, Intel Core Ultra 9 & RTX 3090

**Comment by dluc** [comment]
Looks like a limitation of llamasharp, guessing it might be related to global state and non-thread-safe code?

My suggestion would be opting for ollama or similar

**Comment by aropb** [comment]
And how can I use Ollama?

**Comment by dluc** [comment]
as per other thread, unfortunately the underlying OpenAI connector doesn't work with it. Ollama provides an openai compatible endpoint, but the connector we're using in SK/KM doesn't work 100% with it, throwing exceptions. Someone will need to add a new connector, if needed.

**Comment by aropb** [comment]
And why is only AddSingleton implemented in the class IKernelMemoryBuilder? Why is it not possible to do, for example, AddTransient?

**Comment by dluc** [comment]
Update: KM v0.72 now includes an Ollama connector, making it extremely easier to work with local models

**Comment by aropb** [comment]
I would like to use LLamaSharp specifically.

**Comment by dluc** [comment]
Please check if KM 0.73 release fixes this problem, this release uses the latest packages from LLamaSharp, which could address this bug.

If not, I would report the issue in the LLamaSharp project at https://github.com/SciSharp/LLamaSharp/issues - past versions used to work fine, so something must have changed.

**Comment by aropb** [comment]
For multi-user use, ITextGeneration must be used as an scoped service (AddScoped). But the context is created in the constructor.  Before using scoped object, you need to call a special method to clear the context. 
Please think about these suggestions.

**Comment by dluc** [comment]
Unless the implementation maintains "user request" state across multiple requests, using singletons is fine. 

In Kernel Memory, the only state retained by text generators is the model in use, a common approach across both KM and SK services. 

On the other hand, if your scenario requires a single connector to handle multiple models (something different from KM intent), I recommend using LLamaSharp directly

**Comment by aropb** [comment]
Is there any way to understand that ITextGeneration is used for Summary?
