### ISSUE TITLE
[Bug] Method not found: 'Void Azure.AI.OpenAI.AzureOpenAIClientOptions.set_ApplicationId(System.String)

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/kernel-memory#821]
### Context / Scenario

Following upgrading to `0.76.240930.3`, we started to see errors when we ran our application:

```
[BE]       Error processing document
[BE]       System.MissingMethodException: Method not found: 'Void Azure.AI.OpenAI.AzureOpenAIClientOptions.set_ApplicationId(System.String)'.
[BE]          at Microsoft.KernelMemory.AI.AzureOpenAI.Internals.AzureOpenAIClientBuilder.Build(AzureOpenAIConfig config, HttpClient httpClient, ILoggerFactory loggerFactory)
[BE]          at Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator..ctor(AzureOpenAIConfig config, ITextTokenizer textTokenizer, ILoggerFactory loggerFactory, HttpClient httpClient)
[BE]          at Microsoft.KernelMemory.KernelMemoryBuilderExtensions.WithAzureOpenAITextEmbeddingGeneration(IKernelMemoryBuilder builder, AzureOpenAIConfig config, ITextTokenizer textTokenizer, ILoggerFactory loggerFactory, Boolean onlyForRetrieval, HttpClient httpClient)
```

### What happened?

The error above happens when we try to use the following code (which worked with previous versions of KM):

```cs
        _memory = new KernelMemoryBuilder()
            .WithAzureOpenAITextEmbeddingGeneration(new AzureOpenAIConfig
            {
                APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
                Auth = AzureOpenAIConfig.AuthTypes.AzureIdentity,
                Endpoint = $"https://{openAIClientParametersEmbeddings.CognitiveServicesAccountName}.openai.azure.com/",
                Deployment = openAIClientParametersEmbeddings.DeploymentName
            })
```

### Importance

I cannot use Kernel Memory

### Platform, Language, Versions

.NET 8, Kernel Memory 0.76.240930.3

### Relevant log output

```shell
See above
```

**Comment by dluc** [comment]
That’s an unfortunate side effect of using serverless mode (and beta libraries). This is why we recommend running KM as a service - to keep KM’s internal dependencies separate from your app’s dependencies.

If your code references KM serverless classes and explicitly uses `Azure.AI.OpenAI`, it’s important to align your app with the **same version** KM is using to prevent breaking changes, especially since the Azure OpenAI library is still in beta. The same applies to any other libraries KM depends on, if different versions are used in your solution.

For reference:

* KM currently uses Semantic Kernel 1.21.1
* SK 1.21.1 internally uses Azure.AI.OpenAI **2.0.0-beta.5**
