### ISSUE TITLE
[Bug] SQL throws timeout/sql locked on Kernel Memory operation (add multiple documents, delete index)

### ISSUE THREAD

**Issue by bossbast1** [microsoft/kernel-memory#926]
### Context / Scenario

Hello,

We are having issues with SQL, most likely with the table **[dbo].[KMMemories]**. It's hard to perform any operations on it. Retrieving a large number of entries takes quite some time. For instance, getting 1000 items takes 25 seconds on the first attempt and 10 seconds on subsequent runs, which is quite a lot for such a small number of items (I know the JSONs are big). Deleting an item takes about a second. This wouldn't be the biggest problem if Kernel memory operations didn't cause locks and rollbacks, essentially killing the database for a while.

There are two use cases that cause a problem:

1. Ingestion deadlock retry spiral: If we put too many items in the queue to be uploaded in a short span of time, the database table gets temporarily SQL deadlocked or the timeouts are extremely low (we have schedule job that consumes our repository and puts everything to KM in short time). This results in failed uploads and retriggers, which end up in the same failed result. This basically happens after every single retry again and again. We need to wait for all auto retries to fail or forcefully cut the KM app and keep it down for few mins, which we cannot do in production. Only after letting it rest for a while (after the last attempt) can we try to upload again. Also, it will leave residues, as Storage or Search is able to be loaded fully, but the SQL fails and is not loaded.

2. Unable to delete index with just 150 items: If we call the delete index API, it just times out on SQL, most likely due to the slowness of the delete. This results in rollback and retry, and we get into the retry->lock/timeout->fail loop again. We need to manually go to SQL and call delete all for the index, which took 45 minutes for 1400 items.

The main table has 4800 items, and the index that fails to delete is in the screenshot with just 150 entries.

PS: I suspect you are already working on improving performance, but I just wanted to point out a few annoying use cases.

### What happened?

Expectations are: We should at least be able to delete the index properly without getting a timeout, or upload without getting timeout (it feels like the current timeout is hardly a few seconds). 
Additionally, it would be great if you are able to optimize the table to handle performance better and ensure that multiple indexes do not affect each other (having a DB read/write issue on one index should not block all the indices). Finally, it would be beneficial to handle the retry logic related to SQL of KM better, although that might be challenging to achieve.

### Importance

edge case

### Platform, Language, Versions

Kubernetes App hosting, C# version, Kernel Memory and SQL 0.92.241112.1 (never version has no mention of SQL in changelog)
DB: Azure SQL DB Elastic pool Standard v2 cores

### Relevant log output

```shell
[14:45:09.889] warn: Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline[0] Message '5139450a-2350-4e3c-8bfd-29246b9420ad' processing failed with exception, putting message back in the queue with a delay of 4000 msecs Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.  ---> System.ComponentModel.Win32Exception (258): Unknown error 258

Microsoft.Data.SqlClient.SqlException:
   at Microsoft.Data.SqlClient.SqlConnection.OnError (Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning (Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery (Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal (Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync (Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory+<DeleteIndexAsync>d__10.MoveNext (Microsoft.KernelMemory.MemoryDb.SQLServer, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory+<DeleteIndexAsync>d__10.MoveNext (Microsoft.KernelMemory.MemoryDb.SQLServer, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.Handlers.DeleteIndexHandler+<InvokeAsync>d__7.MoveNext (Microsoft.KernelMemory.Core, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator+<RunPipelineStepAsync>d__8.MoveNext (Microsoft.KernelMemory.Core, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator+<>c__DisplayClass5_0+<<AddHandlerAsync>b__0>d.MoveNext (Microsoft.KernelMemory.Core, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline+<>c__DisplayClass20_0+<<OnDequeue>b__0>d.MoveNext (Microsoft.KernelMemory.Orchestration.AzureQueues, Version=0.92.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3)
Inner exception System.ComponentModel.Win32Exception handled at Microsoft.Data.SqlClient.SqlConnection.OnError:
```

**Comment by bossbast1** [comment]
![Image](https://github.com/user-attachments/assets/ecaa1a19-f38a-4927-a633-63b9d37de299)

**Comment by dluc** [comment]
@marcominerva thoughts?

**Comment by marcominerva** [comment]
> We need to manually go to SQL and call delete all for the index, which took 45 minutes for 1400 items.

According to this statement, this seems a problem related to SQL itself, than directly depending on Kernel Memory.  From your log, I see you're using Azure SQL Database. Could you try using a local SQL Server instance?

The original SQL scripts where authored by @kbeaugrand, do you have any additional idea?

**Comment by bossbast1** [comment]
Just FIY: We do not have this problems on the secondary tables holding the contents of the jsons.

KM**Embeddings**_botone
KM**MemoriesTags**_botone

I would still consider looking into SQL timeouts settings, and if possible slightly increase them to some more reasonable thresholds so "weaker" Database can still manage bigger concurrent load or big amount of data.

In regards to the delete of index, I might try to check the code to see the logic whether the delete really tries to create just one single call to DB to delete everything for that index. Because if that is the case, with the timeout now, which seemed like only few seconds after the delete request was fetched from queue, I don't think even fast DB would be able to make it time, especially if we talk about 10k, 100k items.

**Comment by doug62** [comment]
I'm having trouble finding a way to set the SQL command timeout - wish the code implemented dependency injection.

**Comment by kbeaugrand** [comment]
> I'm having trouble finding a way to set the SQL command timeout - wish the code implemented dependency injection.

@doug62 this should be achieve directly in the SQL connection string, [see related documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-5.2).

@bossbast1 times you mention seems to be very long ! I don't remember having those times when doing my tests (having about 1M entries). I do suspect also some issue on the database itself.
Honestly when doing my load testing used Serverless hosting so it might automatically scale behind...

I could try to take time to try this kind of use case in SQL on an elastic pool to see what is happening there.

On the other hand, could you share us some metrics on the database when doing your operations (IOPS, Data in/out, ...) ?

Really sorry for my late answer.

**Comment by rainmakerho** [comment]
@doug62 
The current way can only add the code by setting the \"CommandTimeout\" as follows:
```
SqlCommand command = connection.CreateCommand();
//Set CommandTimeout
command.CommandTimeout = 600;
command.CommandText = sql;
```

**Comment by marcominerva** [comment]
@rainmakerho The connection string allows to set also the Command Timeout:

![Image](https://github.com/user-attachments/assets/f165dd6a-dc2c-4ffb-8646-a5f41a7b9c95)

So, you can use something like this:

`"Data Source=(local);Integrated Security=true;Initial Catalog=Chinook;Command Timeout=300"`

**Comment by coryisakson** [comment]
@kbeaugrand and @marcominerva - hello guys, I am running into the SQL deadlock issue as well. I was able to reproduce it on local SQL with just a few documents. They are each about 300 pages so plenty of document partitions being processed simultaneously by the Queues. I suspect the PrepareUpsertRecordsBatchQuery because the error is happening during UpsertBatchAsync. This is top priority to resolve for my customer so appreciate any ideas to address it.

**Comment by coryisakson** [comment]
@marcominerva  - Locally I am using SQL without Native Vector support. Same issue on our Azure SQL deployment with Native Vector support enabled.

I tried a CommandTimeout of 600 via Connection string (locally) and it did not make any difference.

"MemoryDbUpsertBatchSize" is set to 1. I think the issue is that multiple Queue messages are being processed at the same time and trying to update the same table.

**Comment by marcominerva** [comment]
Can you share the Stack Trace of the Exception?

**Comment by coryisakson** [comment]
warn: Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline[0]
      Message 'dacdc5b7-be07-44bf-a55b-3944b7155d77' processing failed with exception, putting message back in the queue with a delay of 34000 msecs
      Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 53) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
         at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveRecordAsync(DataPipeline pipeline, IMemoryDb db, MemoryRecord record, HashSet`1 createdIndexes, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator.RunPipelineStepAsync(DataPipeline pipeline, IPipelineStepHandler handler, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator.<>c__DisplayClass5_0.<<AddHandlerAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline.<>c__DisplayClass20_0.<<OnDequeue>b__0>d.MoveNext()
      ClientConnectionId:48c56bbf-35eb-4a0a-abe3-285b2811adad
      Error Number:1205,State:128,Class:13

**Comment by coryisakson** [comment]
I added an Index for the [key] column and tested the large file uploads again and same issue with just 2 running at the same time.

warn: Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline[0]
      Message '81b4c45c-dd2f-4874-a328-6bfc701a8121' processing failed with exception, putting message back in the queue with a delay of 7000 msecs
      Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
         at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
         at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertBatchAsync(String index, IEnumerable`1 records, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.MemoryDb.SQLServer.SqlServerMemory.UpsertAsync(String index, MemoryRecord record, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.SaveRecordAsync(DataPipeline pipeline, IMemoryDb db, MemoryRecord record, HashSet`1 createdIndexes, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Handlers.SaveRecordsHandler.InvokeAsync(DataPipeline pipeline, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator.RunPipelineStepAsync(DataPipeline pipeline, IPipelineStepHandler handler, CancellationToken cancellationToken)
         at Microsoft.KernelMemory.Pipeline.DistributedPipelineOrchestrator.<>c__DisplayClass5_0.<<AddHandlerAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.KernelMemory.Orchestration.AzureQueues.AzureQueuesPipeline.<>c__DisplayClass20_0.<<OnDequeue>b__0>d.MoveNext()
      ClientConnectionId:32eeaf77-5f63-48ac-bb52-db976018eeb8
      Error Number:1205,State:128,Class:13
