### ISSUE TITLE
Unable to get web service running locally

### ISSUE THREAD

**Issue by R0315** [microsoft/kernel-memory#99]
I am trying to get SM service running locally so I can refactor my project to use the v1 SK release, but I can't get it working. I've followed everything that I see on the readme, and I've ensured the env variable is set to "Development". Below is what happens when i try to run the service. I am getting an error about an empty string value for the Parametr 'modelId'.

I searched "modelId" and saw no other issues raised. Is there some step missing in the readme that I wouldn't know to take?

```powershell
PS **\semantic-memory\dotnet\Service> ./run
  Determining projects to restore...
  All projects are up-to-date for restore.
MSBuild version 17.7.3+8ec440e68 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  ClientLib -> **\semantic-memory\dotnet\ClientLib\bin\Debug\netstandard2.0\Microsoft.SemanticMemory.Client.dll
  CoreLib -> **\semantic-memory\dotnet\CoreLib\bin\Debug\net6.0\Microsoft.SemanticMemory.Core.dll
  InteractiveSetup -> **\semantic-memory\dotnet\InteractiveSetup\bin\Debug\net6.0\Microsoft.SemanticMemory.InteractiveS
  etup.dll
  Service -> **\semantic-memory\dotnet\Service\bin\Debug\net6.0\Microsoft.SemanticMemory.Service.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.44
Unhandled exception. System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'modelId')
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.AzureOpenAIClientBase..ctor(String modelId, String endpoint, TokenCredential credential, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.AzureTextEmbeddingGeneration..ctor(String modelId, String endpoint, TokenCredential credential, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__0(IServiceProvider serviceProvider) in **\semantic-memory\dotnet\CoreLib\AI\AzureOpenAI\DependencyInjection.cs:line 38
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)   at Microsoft.SemanticMemory.MemoryClientBuilder.FromConfiguration(SemanticMemoryConfig config, IConfiguration servicesConfiguration) in **\semantic-memory\dotnet\CoreLib\AppBuilders\MemoryClientBuilder.cs:line 304
   at Microsoft.SemanticMemory.MemoryClientBuilder.FromAppSettings(String settingsDirectory) in **\semantic-memory\dotnet\CoreLib\AppBuilders\MemoryClientBuilder.cs:line 218
   at Program.<Main>$(String[] args) in **\semantic-memory\dotnet\Service\Program.cs:line 42
PS **\semantic-memory\dotnet\Service>
```

**Comment by dluc** [comment]
@R0315 I'm unable to reproduce the same error, could you provide a copy of your settings (removing secrets)? by any chance are you using also env vars to override some config?

**Comment by R0315** [comment]
> @R0315 I'm unable to reproduce the same error, could you provide a copy of your settings (removing secrets)? by any chance are you using also env vars to override some config?

All of the recent updates may have addressed this. I have to be pulled away from my project that uses kernel memory for a bit, but I will endeavor to test this and get back to you here when I can.

**Comment by dluc** [comment]
Please let us know if the issue is still present, we can reopen the issue. Thanks
